'''
Bot Configration
'''
COMMAND_PREFIX = '.'
MINECRAFT_SERVER_OFFLINE_ALERT_CHANNEL_IDS = []
MINECRAFT_SERVER_OFFLINE_ALERT_MENTIONED_USER_IDS = []


'''
Minecraft server infomation
'''
MINECRAFT_SERVER_ADDRESS = 'localhost'
MINECRAFT_SERVER_PORT = 25565


'''
Discord TOKEN
'''
DISCORD_BOT_TOKEN = ''
